---
title: "M11 Exercises"
author: "Matt Scheffel"
date: "2022-11-09"
output: html_document
---

# 11.1

```{r}
library(tidyverse)
```

# 11.2

```{r}
scores <- 
  tibble(
    name = c("mike", "carol", "greg", "marcia", "peter", "jan", "bobby", "cindy", "alice"),
    school = c("south", "south", "south", "south", "north", "north", "north", "south", "south"),
    teacher = c("johnson", "johnson", "johnson", "johnson",  "smith", "smith", "smith", "perry", "perry"),
    sex = c("male", "female", "male", "female", "male", "female", "male", "female", "female"),
    math_score = c(4, 3, 2, 4, 3, 4, 5, 4, 5),
    reading_score = c(1, 5, 2, 4, 5, 4, 1, 5, 4)
)
```


# 11.3

```{r}

```

# 11.4

```{r}
scores %>%
  slice(1:3)
```

# 11.5 

```{r}
scores %>%
  arrange(desc(math_score))
```

# 11.6

```{r}
scores %>%
  arrange(name)
```

# 11.7

```{r}
scores %>%
  arrange(sex)
```

Females.

# 11.8

```{r}
scores %>%
  arrange(school, teacher, sex, math_score, reading_score)
```


# 11.9

```{r}
scores %>%
  select(name, math_score, reading_score)
```

# 11.10

```{r}
scores %>%
  select(-sex)
```

# 11.11

```{r}
scores %>%
  select(-sex, -reading_score)
```

# 11.12

```{r}
scores %>%
  select(sex, everything())
```

# 11.13

```{r}
scores %>%
  filter(sex == "male" & school == "south")
```

# 11.14

```{r}
scores %>%
  filter (math_score > mean(math_score))
```

# 11.15

```{r}
scores %>%
  filter(math_score >= 4 & reading_score >= 3)
```

# 11.16

```{r}
scores %>%
  filter(math_score <= 3 | reading_score <= 3)
```

# 11.17

```{r}
scores %>%
  filter(reading_score %in% 2:4)
```

# 11.18

```{r}
scores %>%
  filter(substr(name,1,1) == 'm')
```

# 11.19

```{r}
scores %>%
  group_by(teacher) %>%
  filter(max(math_score) ==  5)
```

#11.33

```{r}
scores %>%
  group_by(teacher) %>%
  summarize(max_math_score = max(math_score))
```

